# Generated by Django 2.1.5 on 2020-02-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200226_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='authorization',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='plainText',
        ),
        migrations.AddField(
            model_name='posts',
            name='content',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='posts',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='posts',
            name='visibilities',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='visible_to',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='posts',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
