# Generated by Django 2.1.5 on 2020-02-25 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friends', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='extendauthormodel',
            name='authorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extendauthormodel',
            name='friendID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendID', to=settings.AUTH_USER_MODEL),
        ),
    ]
